### ISSUE TITLE
about V_list and N_list

### ISSUE THREAD

**Issue by FrankYoungchen** [facebookresearch/PoseWarper#11]
hi，I don't quite understand why use different V_list and N_list，Can you explain it，please？

**Comment by gberta** [comment]
It's for the ablation studies depicted in Figure 4 of the paper. V_list represents how many labeled videos we will use during training, whereas N_list represents how many labeled frames per video we will use during training.

**Comment by FrankYoungchen** [comment]
Thanks，I understand it.
