### ISSUE TITLE
The performance of the baseline model

### ISSUE THREAD

**Issue by ihollywhy** [facebookresearch/PoseWarper#14]
Hi, 

I run the exps on posetrack17 and posetrack18 and got the following mAP results:

| mAP   |      posetrack17      |  posetrack18 |
|----------|:-------------:|------:|
| Baseline (HRNet) |  80.9 | 79.4 |
| PoseWarper |    81.6   |  79.9 |

I check the code and find the baseline model seems to be the original HRNet. But the performance of this baseline should not be that good ... I got confused.

Does anyone have any idea about these results, especially for the baseline model?

**Comment by gberta** [comment]
We use much higher quality person detection proposals, which significantly improves the performance of both methods.

**Comment by ihollywhy** [comment]
Oh, thanks for solving my confusion. It makes sense.
