### ISSUE TITLE
About Supplementary data files

### ISSUE THREAD

**Issue by chenhaomingbob** [facebookresearch/PoseWarper#15]
Thank you for your wonderful works.
I am curious about the precomputed boxes json files under 'posetrack 17/18_precomputed_boxes' folder.
Can you describe how these boxes were computed?
Thank you very much.

**Comment by gberta** [comment]
I used a Cascaded R-CNN based on ResNeXt-101, which was pretrained on COCO, to extract person bounding boxes.

**Comment by chenhaomingbob** [comment]
Thank you 😄

> I used a Cascaded R-CNN based on ResNeXt-101, which was pretrained on COCO, to extract person bounding boxes.
