### ISSUE TITLE
How to train this model on other datasets?

### ISSUE THREAD

**Issue by ghost** [facebookresearch/PoseWarper#17]
Hello, thanks for your code. I've got the val results on posetrack17 and posetrack18.
But I want to train this model on other datasets, such as penn action, to test its generalization ability and use the method as a baseline.
Could you give me some advice on this? thank you.

**Comment by gberta** [comment]
You need to create a JSON file for your new dataset using the COCO pose detection format. This is how our JSON files are formatted as well, so you can use them as a reference. Afterwards, training should be straightforward as you should be able to use our code (potentially with some minor modifications) but just with different JSON input data files.
