### ISSUE TITLE
Interpreting Learned Offsets

### ISSUE THREAD

**Issue by chenhaomingbob** [facebookresearch/PoseWarper#19]
Hi,

Thanks for your works.While I am curious about the Figure5 in the paper. How you visualize the motion offsets? 
It follows "Visualizing and Understanding Convolutional Networks" to use deconv layers?

I really hope you can solve my confusion 😊

**Comment by gberta** [comment]
We use the same code as for visualizing optical flow. Each pair of consecutive channels in the offsets defines an offset flow that we can visualize.

**Comment by chenhaomingbob** [comment]
Your method posewarper follows top-down framework. But In Figure 5 of your paper, why your visualized result is on the global image (multi-person image)? can you tell me the detail ? 
![image](https://user-images.githubusercontent.com/18526439/102317350-5ce25f00-3fb2-11eb-8ca9-0fca2e315095.png)
