### ISSUE TITLE
Why don't you use ground truth heatmaps to train the PoseWarper

### ISSUE THREAD

**Issue by ArchNew** [facebookresearch/PoseWarper#23]
Why don't you use the ground truth of frame A and frame B as input and train the PoseWarper? I think this will give you a more accurate PoseWarper. 

The only reason I can think of is that it should work on a sparsely annotated dataset. Such a dataset might not have enough neighboring labeled frames for the model to train if we should use ground truth information to train the PoseWarper.

If I want to test your model's validity, could I use ground truth heatmaps as input and train the model?

**Comment by gberta** [comment]
The model needs to learn how to deal with inaccurate/uncertain predictions. If you use ground truth pose heatmaps during training, but then use predicted pose heatmaps during inference, you will be creating a big gap between these two stages, and therefore, it would likely not work very well. It is my opinion, that the training and inference stages should be made as similar as possible. 

Having said this, I would suggest to try using ground truth heatmaps as input to train the model. It would be useful to see what will happen. If you do it, please report your finding here. I would be curious to know as well.

**Comment by ArchNew** [comment]
You are absolutely right if we use the heatmaps generated by the pose estimator during inference. However, from what I can tell, the paper's primary application scenario is to label the sparsely-labeled datasets with ground truth heatmaps as input. At least two experiments are dedicated to this topic. Even figure 1 in the paper demonstrates this concept. That's where my question stemmed from.

I plan to do experiments on the PoseWarper using ground truth heatmaps as input. I'll report the results if I have something. Personally, I think the PoseWarper as a research tool can be a lighter and more competitive replacement for the deep-net-based optic flow estimators in many areas.

**Comment by gberta** [comment]
That's an excellent point! And yes, I agree that PoseWarper could be used as a lighter alternative to CNN based optical flow estimators. Please let me know if these experiments yield any interesting results.
