### ISSUE TITLE
Your code might have one minor bug.

### ISSUE THREAD

**Issue by ArchNew** [facebookresearch/PoseWarper#27]
![image](https://user-images.githubusercontent.com/11910381/101458924-824be900-3972-11eb-9c59-9db880161a61.png)
After fixing a minor bug, I reached this result with an input resolution of 256x192.
And with all the bells and whistles that HRNet offered, I'm sure the results could increase by another 3 points.

The bug is 'neck'. Posetrack actually offered 'neck' coordinates to be trained. However, your code manually computes the 'neck' via the left and right shoulders. This brings down at least 1.5 Total points.

**Comment by gberta** [comment]
Yes, I'm aware that we computed some keypoints in an ad-hoc fashion, which probably leads to suboptimal results. That's awesome that you were able to improve it by such a substantial margin!

**Comment by ArchNew** [comment]
It seems you use deformable Conv as a projector, to project pixels from one place from Frame B to another place in Frame A according to the offset calculated by a stack of residual blocks. It's a rather novel way to use deformable convolution, at least, for me.
