### ISSUE TITLE
About the Figure 5

### ISSUE THREAD

**Issue by chenhaomingbob** [facebookresearch/PoseWarper#29]
Your method posewarper follows top-down framework. But In Figure 5 of your paper, why your visualized result show on the global image (multi-person image)? can you tell me the details ? 
![image](https://user-images.githubusercontent.com/18526439/102317350-5ce25f00-3fb2-11eb-8ca9-0fca2e315095.png)

**Comment by gberta** [comment]
Yes, in practice we use a top-down two-stage approach. However, our framework is also general enough to be applied on the full image resolution. Thus, to capture more context, for visualization purposes, I ran our model on the full image resolution.

**Comment by chenhaomingbob** [comment]
Thank you for solving my doubts in time .👍

**Comment by lxtGH** [comment]
Hi! @gberta Is fig5 the same as your previous paper: Learning Discriminative Motion Features Through Detection ?
