### ISSUE TITLE
error: command '/usr/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by yinizhizhu** [facebookresearch/PoseWarper#3]
I followed the instructions of installation. When I ran "python setup.py develop", I got an error reporting: "error: command '/usr/bin/nvcc' failed with exit status 1". Is there any idea to fix this?

Thanks!

**Comment by gberta** [comment]
It seems that this might be due to using CUDA 10.1 (see https://github.com/open-mmlab/mmdetection/issues/1374). I used CUDA 10.0, and it worked fine. Therefore, I'd suggest to downgrade your CUDA version to 10.0

**Comment by yinizhizhu** [comment]
Thanks for your quick reply!

I am working on Pose-based Tracking.
Can I get some means of obtaining the pose estimation results on PoseTrack17 & PoseTrack18  (Validation & Test)?
I would be very grateful if the pose estimation results are available.

**Comment by yinizhizhu** [comment]
Thanks for your quick reply!

I am working on Pose-based Tracking.
Can I get some means of obtaining the pose estimation results on PoseTrack17 & PoseTrack18 (Validation & Test)?
I would be very grateful if the pose estimation results are available.

**Comment by iamshri8** [comment]
@gberta  Hi, I tried with CUDA 10.0.130(using conda install cudatoolkit) and still i get the same error as mentioned in [https://github.com/open-mmlab/mmdetection/issues/1374#](https://github.com/open-mmlab/mmdetection/issues/1374#)

**Comment by gberta** [comment]
The scripts in the codebase perform evaluation on PoseTrack 17 and 18 datasets. The evaluation is done immediately after testing stage. If you run the scripts, you should see the printed tables with the mAP results for each joint.

**Comment by yinizhizhu** [comment]
This repo seems not to provide the specific code for testing on the testing set. What should I do to get the pose estimation results on the testing set? While file should I modify?

Thanks!
