### ISSUE TITLE
About PoseTrack2017 Test set

### ISSUE THREAD

**Issue by chenhaomingbob** [facebookresearch/PoseWarper#6]
Thank you for your wonderful works. 
 I download the  PoseTrack2017 Test set from [https://posetrack.net/data/test.tar.gz](https://posetrack.net/data/test.tar.gz). But I see the JSON files are not having any ground truth information. 
So I hope to know how you do the experiment about pose propagation in the PoseTrack2017 Test set?
I would appreciate it if you could reply to me in your busy schedule.

**Comment by gberta** [comment]
Video pose propagation requires sparse ground truth annotations. Since ground truth annotations are not released for the PoseTrack17 test set do we only performed it on the validation set.
