### ISSUE TITLE
Where is the models module?

### ISSUE THREAD

**Issue by brandhaug** [facebookresearch/PoseWarper#8]
The module `models` doesn't seem to be in the project, which causes `posetrack18_helper.py` to crash:

```
File "PoseWarper/tools/train.py", line 37, in <module>
    import models
ModuleNotFoundError: No module named 'models'
```

**Comment by gberta** [comment]
The "models" module is one of the directories provided with the repo. I believe that you might have missed one of the installation steps, and therefore your paths are not set properly. Please follow the instructions carefully, and I think this issue should be resolved.

**Comment by brandhaug** [comment]
You're right. I made a custom folder called models, and added it to .gitignore. This also affected the models folder in lib.
