### ISSUE TITLE
Could I ask a question about the motion offset?

### ISSUE THREAD

**Issue by fandulu** [facebookresearch/PoseWarper#9]
Hello, thanks for sharing this wonderful code. I have a question referred to pose_hrnet.py. It seems that motion offsets are not explicitly predicted, instead, they are a kind of implicit feature. This is different from predicting a flow map and then performs F.grid_sample. Is it correct?

**Comment by gberta** [comment]
Yes, the motion offsets are implicitly predicted by directly optimizing the pose estimation objective. This is indeed different than predicting optical flow explicitly and performing F.grid_sample. Our experiments suggest that using our offsets produces much better performance than using optical flow.

**Comment by fandulu** [comment]
Thanks
